# Generated by Django 4.1.3 on 2023-11-17 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("listing_owner", "0001_initial"),
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="hotel",
        ),
        migrations.AlterField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="listing_owner.room"
            ),
        ),
        migrations.DeleteModel(
            name="Hotel",
        ),
        migrations.DeleteModel(
            name="Room",
        ),
    ]
