# Generated by Django 4.1.3 on 2023-11-17 13:05

from django.db import migrations


def create_initial_data_in_database(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Hotel = apps.get_model("listing_owner", "Hotel")
    Room = apps.get_model("listing_owner", "Room")
    hotel1 = Hotel.objects.create(name="hotel1", owner="owner1", star=4)
    hotel2 = Hotel.objects.create(name="hotel2", owner="owner2", star=5)
    for hotel in [hotel1, hotel2]:
        for item in range(5):
            Room.objects.create(hotel=hotel, name=f"room{item+1}", beds=item + 1)


class Migration(migrations.Migration):
    dependencies = [
        ("listing_owner", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_data_in_database),
    ]
